/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int URL = 3;
  /** RegularExpression Id. */
  int CORREO = 4;
  /** RegularExpression Id. */
  int IDENTIFIER = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<NUMBER>",
    "<URL>",
    "<CORREO>",
    "<IDENTIFIER>",
    "\" \"",
    "\" \\t \"",
    "\" \\r \"",
    "\" \\n \"",
  };

}
